spring.config.import=optional:file:.env[.properties]





# MongoDB Atlas Connection
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/helpify}


server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
